# Generated by Django 5.0.6 on 2024-07-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_userprofile_bio_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
