# Generated by Django 5.0.6 on 2024-07-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_rename_location_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='roadmap',
            field=models.TextField(blank=True),
        ),
    ]
